"use client";

import { useEffect, useMemo, useState } from "react";
import { getHighExposureLoanAccounts, isActionOverdue, isClosedActionStatus, isWatchlistStatus } from "@/lib/riskPolicy";
import type { PortalClarification } from "@/lib/portalRouting";

type Loan = { loan_account:string; member_name:string; branch?:string; loan_product?:string; employer?:string; sector?:string; outstanding_balance:number; arrears_amount?:number; risk_status:"Green"|"Amber"|"Red"|"NPL" };
type Action = { action_id?:string; loan_account:string; member_name:string; risk_status?:string; assigned_to?:string; due_date?:string; status?:string; escalation_level?:string };
type Props = { currency:string; requests:PortalClarification[] };
const read=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||"") as T}catch{return fallback}};

export default function CeoExecutiveInsights({currency,requests}:Props){
 const[records,setRecords]=useState<Loan[]>([]);const[actions,setActions]=useState<Action[]>([]);
 useEffect(()=>{setRecords(read("kiprod_loan_records",[]));setActions(read("kiprod_action_items",[]))},[]);
 const data=useMemo(()=>{
  const watchlist=records.filter(r=>isWatchlistStatus(r.risk_status));const highIds=getHighExposureLoanAccounts(watchlist);const high=[...watchlist].filter(r=>highIds.has(r.loan_account)).sort((a,b)=>b.outstanding_balance-a.outstanding_balance);const arrears=records.reduce((s,r)=>s+Number(r.arrears_amount||0),0);const outstanding=records.reduce((s,r)=>s+Number(r.outstanding_balance||0),0);
  const open=actions.filter(a=>!isClosedActionStatus(a.status));const week=new Date();week.setDate(week.getDate()+7);const dueThisWeek=open.filter(a=>{if(!a.due_date)return false;const d=new Date(`${a.due_date}T23:59:59`);return d>=new Date()&&d<=week});
  const managerMap=new Map<string,{open:number;overdue:number;escalated:number}>();open.forEach(a=>{const owner=String(a.assigned_to||"Unassigned").trim()||"Unassigned";const row=managerMap.get(owner)||{open:0,overdue:0,escalated:0};row.open++;if(isActionOverdue(a))row.overdue++;if(/Level [34]/.test(String(a.escalation_level||"")))row.escalated++;managerMap.set(owner,row)});const managers=[...managerMap.entries()].map(([name,v])=>({name,...v})).sort((a,b)=>b.overdue-a.overdue||b.open-a.open);
  const group=(field:"branch"|"loan_product"|"employer"|"sector")=>{const m=new Map<string,{accounts:number;exposure:number}>();watchlist.forEach(r=>{const name=String(r[field]||"Not recorded");const v=m.get(name)||{accounts:0,exposure:0};v.accounts++;v.exposure+=Number(r.outstanding_balance||0);m.set(name,v)});return [...m.entries()].map(([name,v])=>({name,...v})).sort((a,b)=>b.exposure-a.exposure).slice(0,5)};
  return{watchlist,high,arrears,outstanding,dueThisWeek,managers,branches:group("branch"),products:group("loan_product"),employers:group("employer"),sectors:group("sector")};
 },[records,actions]);
 const money=(v:number)=>`${currency} ${Number(v||0).toLocaleString("en-KE",{maximumFractionDigits:0})}`;const decisions=requests.filter(r=>r.status==="Escalated"||r.status==="Further Clarification Required"||r.status==="Closed").slice(0,6);
 const concentration=(title:string,rows:{name:string;accounts:number;exposure:number}[])=><article className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-black">{title}</h3><div className="mt-3 space-y-3">{rows.map((r,i)=><div key={r.name} className="grid grid-cols-[24px_1fr_auto] gap-2 text-sm"><span className="font-black text-slate-400">{i+1}</span><span className="truncate font-semibold">{r.name}</span><span className="text-right"><b>{money(r.exposure)}</b><small className="block text-slate-500">{r.accounts} accounts</small></span></div>)}</div></article>;
 return <section className="space-y-7">
  <div className="grid gap-6 xl:grid-cols-[1fr_1fr]"><article className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-wide text-emerald-700">Portfolio movement</p><h2 className="mt-2 text-2xl font-black">Reporting-period position</h2><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-slate-100 p-4"><p className="text-xs font-bold text-slate-500">Total arrears</p><p className="mt-2 text-xl font-black text-red-700">{money(data.arrears)}</p><p className="text-xs text-slate-500">{data.outstanding?((data.arrears/data.outstanding)*100).toFixed(1):"0.0"}% of outstanding</p></div><div className="rounded-2xl bg-slate-100 p-4"><p className="text-xs font-bold text-slate-500">Previous-period trend</p><p className="mt-2 text-xl font-black">Baseline</p><p className="text-xs text-slate-500">Activates after the next reporting-period snapshot</p></div></div></article><article className="rounded-3xl bg-[#0b1d33] p-6 text-white shadow-sm"><p className="text-xs font-black uppercase tracking-wide text-emerald-300">Immediate executive deadlines</p><h2 className="mt-2 text-2xl font-black text-white">Actions due this week</h2><p className="mt-3 text-5xl font-black text-white">{data.dueThisWeek.length}</p><div className="mt-4 space-y-2">{data.dueThisWeek.slice(0,4).map(a=><div key={a.action_id||a.loan_account} className="rounded-xl bg-white/5 p-3 text-sm"><b>{a.loan_account}</b> · {a.assigned_to||"Unassigned"}<span className="float-right">{a.due_date}</span></div>)}</div></article></div>
  <div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Concentration intelligence</p><h2 className="mt-1 text-2xl font-black">Watchlist exposure concentrations</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{concentration("Top branches",data.branches)}{concentration("Top products",data.products)}{concentration("Top employers",data.employers)}{concentration("Top sectors",data.sectors)}</div></div>
  <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><article className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">Accountability by manager</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="p-3">Manager / function</th><th className="p-3">Open</th><th className="p-3">Overdue</th><th className="p-3">Escalated</th></tr></thead><tbody>{data.managers.map(r=><tr key={r.name} className="border-b"><td className="p-3 font-bold">{r.name}</td><td className="p-3">{r.open}</td><td className="p-3 font-black text-red-700">{r.overdue}</td><td className="p-3">{r.escalated}</td></tr>)}</tbody></table></div></article><article className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">Board instructions and decisions</h2><div className="mt-4 space-y-3">{decisions.map(r=><div key={r.id} className="rounded-2xl border p-4"><div className="flex justify-between gap-2"><b>{r.request_title}</b><span className="text-xs font-black">{r.status}</span></div><p className="mt-2 text-xs text-slate-600">{r.loan_account||"No account"} · {r.assigned_to||"Management"}</p><p className="mt-2 line-clamp-2 text-sm">{r.board_review_notes||"No Board decision note recorded."}</p></div>)}{!decisions.length&&<p className="rounded-2xl border border-dashed p-4 text-sm text-slate-600">No completed or escalated Board instruction is currently recorded.</p>}</div></article></div>
  <article className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">Top high-exposure Watchlist accounts</h2><p className="mt-1 text-sm text-slate-600">Top 10 outstanding exposures within the approved Watchlist.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="p-3">Account</th><th className="p-3">Member</th><th className="p-3">Risk</th><th className="p-3">Exposure</th></tr></thead><tbody>{data.high.map(r=><tr key={r.loan_account} className="border-b"><td className="p-3 font-bold">{r.loan_account}</td><td className="p-3">{r.member_name}</td><td className="p-3 font-black">{r.risk_status}</td><td className="p-3">{money(r.outstanding_balance)}</td></tr>)}</tbody></table></div></article>
 </section>;
}
