"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import Pagination from "../../components/Pagination";
import RegisterSearch from "../../components/RegisterSearch";
import {isActionOverdue,isClosedActionStatus} from "@/lib/riskPolicy";

type Action={action_id?:string;loan_account:string;member_name:string;risk_status?:string;risk_source?:string;action_required?:string;assigned_to?:string;due_date?:string;status?:string;escalation_level?:string;notes?:string};
type Filter="open"|"overdue"|"credit-review"|"escalated"|"assigned";const PAGE_SIZE=15;
const labels:Record<Filter,string>={open:"All Open Credit Actions",overdue:"Overdue Credit Actions","credit-review":"Level 2 Credit Reviews",escalated:"Senior Escalations",assigned:"Assigned to Credit Manager"};
const assignedToCredit=(action:Action)=>String(action.assigned_to||"").toLowerCase().includes("credit");
export default function CreditManagerActionsPage(){const[actions,setActions]=useState<Action[]>([]);const[filter,setFilter]=useState<Filter>("open");const[query,setQuery]=useState("");const[page,setPage]=useState(1);
useEffect(()=>{const requested=new URLSearchParams(window.location.search).get("filter") as Filter|null;if(requested&&requested in labels)setFilter(requested);try{setActions(JSON.parse(localStorage.getItem("kiprod_action_items")||"[]") as Action[])}catch{setActions([])}},[]);
const matches=(action:Action,selected:Filter)=>{if(isClosedActionStatus(action.status))return false;if(selected==="overdue")return isActionOverdue(action);if(selected==="credit-review")return String(action.escalation_level||"").includes("Level 2");if(selected==="escalated")return /Level [34]/.test(String(action.escalation_level||""));if(selected==="assigned")return assignedToCredit(action);return true};
const category=useMemo(()=>actions.filter((action)=>matches(action,filter)),[actions,filter]);const filtered=useMemo(()=>{const term=query.trim().toLowerCase();if(!term)return category;return category.filter((action)=>[action.action_id,action.loan_account,action.member_name,action.risk_status,action.risk_source,action.action_required,action.assigned_to,action.status,action.escalation_level,action.notes].some((value)=>String(value||"").toLowerCase().includes(term)))},[category,query]);const visible=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
const choose=(next:Filter)=>{setFilter(next);setPage(1);setQuery("");window.history.replaceState(null,"",`/credit-manager-portal/actions?filter=${next}`)};
return <main className="min-h-screen bg-slate-100 p-4 text-slate-950 sm:p-8"><div className="mx-auto max-w-[1500px] space-y-6"><header className="rounded-3xl bg-[#071426] p-7 text-white shadow-xl"><p className="text-xs font-black uppercase tracking-[.2em] text-amber-300">Credit Manager Portal · Execution accountability</p><h1 className="mt-2 text-3xl font-black">{labels[filter]}</h1><p className="mt-3 text-slate-300">The existing Execution Tracker remains the master record. Displayed 15 actions per page.</p><Link href="/credit-manager-portal#actions" className="mt-5 inline-flex rounded-xl border border-amber-400/50 px-4 py-2 text-sm font-black text-amber-300">Back to Credit Dashboard</Link></header>
<section className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-wrap gap-2">{(Object.keys(labels) as Filter[]).map((key)=><button key={key} type="button" onClick={()=>choose(key)} className={`rounded-full px-4 py-2 text-sm font-black ${filter===key?"bg-slate-950 text-white":"border bg-white text-slate-700"}`}>{labels[key]} ({actions.filter((action)=>matches(action,key)).length})</button>)}</div><div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase text-slate-500">Matching actions</p><p className="mt-1 text-4xl font-black">{category.length}</p></div><div className="w-full max-w-xl"><RegisterSearch value={query} onChange={(value)=>{setQuery(value);setPage(1)}} placeholder="Search action, account, borrower, owner or escalation" resultCount={filtered.length}/></div></div>
<div className="mt-6 overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500">{["Action ID","Account","Borrower","Risk","Source","Action required","Owner","Due date","Position","Escalation"].map((head)=><th key={head} className="px-3 py-3">{head}</th>)}</tr></thead><tbody>{visible.map((action)=><tr key={action.action_id||action.loan_account} className="border-b"><td className="px-3 py-3 font-bold">{action.action_id||"Legacy"}</td><td className="px-3 py-3">{action.loan_account}</td><td className="px-3 py-3">{action.member_name}</td><td className="px-3 py-3 font-bold">{action.risk_status||"Not set"}</td><td className="px-3 py-3">{action.risk_source||"Portfolio"}</td><td className="max-w-xs px-3 py-3">{action.action_required||"Follow-up required"}</td><td className="px-3 py-3">{action.assigned_to||"Unassigned"}</td><td className="px-3 py-3">{action.due_date||"Not set"}</td><td className={`px-3 py-3 font-black ${isActionOverdue(action)?"text-red-700":""}`}>{isActionOverdue(action)?"Overdue":action.status||"Open"}</td><td className="px-3 py-3">{action.escalation_level||"Not set"}</td></tr>)}</tbody></table>{!visible.length&&<p className="py-10 text-center text-slate-500">No actions match this category.</p>}</div><Pagination page={page} pageSize={PAGE_SIZE} totalItems={filtered.length} onPageChange={setPage}/></section></div></main>}
