"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import Pagination from "../../components/Pagination";
import RegisterSearch from "../../components/RegisterSearch";
import {getHighExposureLoanAccounts,isPar90,isRestructured,isWatchlistStatus} from "@/lib/riskPolicy";
type Loan={member_name:string;loan_account:string;branch?:string;loan_product?:string;employer?:string;outstanding_balance:number;arrears_amount?:number;days_in_arrears?:number;responsible_officer?:string;repayment_status?:string;restructured?:string;risk_flags?:string[];risk_status:"Green"|"Amber"|"Red"|"NPL"};
type Filter="npl"|"red-handoff"|"par90"|"high-exposure"|"restructured"|"unassigned"|"watchlist";const PAGE_SIZE=15;
const labels:Record<Filter,string>={npl:"NPL Recovery Register","red-handoff":"Pre-NPL Handoff · Red","par90":"PAR90 Accounts · 91+ DPD","high-exposure":"High-Exposure NPL","restructured":"Restructured NPL","unassigned":"Unassigned NPL","watchlist":"Complete Watchlist Context"};
export default function RecoveryAccountsPage(){const[records,setRecords]=useState<Loan[]>([]);const[filter,setFilter]=useState<Filter>("npl");const[query,setQuery]=useState("");const[page,setPage]=useState(1);useEffect(()=>{const requested=new URLSearchParams(window.location.search).get("filter") as Filter|null;if(requested&&requested in labels)setFilter(requested);try{setRecords(JSON.parse(localStorage.getItem("kiprod_loan_records")||"[]") as Loan[])}catch{setRecords([])}},[]);const highExposure=useMemo(()=>getHighExposureLoanAccounts(records),[records]);const matches=(record:Loan,selected:Filter)=>{if(selected==="red-handoff")return record.risk_status==="Red";if(selected==="par90")return isPar90(record.days_in_arrears);if(selected==="high-exposure")return record.risk_status==="NPL"&&highExposure.has(record.loan_account);if(selected==="restructured")return record.risk_status==="NPL"&&isRestructured(record);if(selected==="unassigned")return record.risk_status==="NPL"&&!String(record.responsible_officer||"").trim();if(selected==="watchlist")return isWatchlistStatus(record.risk_status);return record.risk_status==="NPL"};const category=useMemo(()=>records.filter((record)=>matches(record,filter)),[records,filter,highExposure]);const filtered=useMemo(()=>{const term=query.trim().toLowerCase();if(!term)return category;return category.filter((record)=>[record.member_name,record.loan_account,record.branch,record.loan_product,record.employer,record.responsible_officer,record.repayment_status,record.risk_status,...(record.risk_flags||[])].some((value)=>String(value||"").toLowerCase().includes(term)))},[category,query]);const visible=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);const money=(value:number)=>`KES ${Number(value||0).toLocaleString("en-KE",{maximumFractionDigits:0})}`;const choose=(next:Filter)=>{setFilter(next);setPage(1);setQuery("");window.history.replaceState(null,"",`/recovery-manager-portal/accounts?filter=${next}`)};
return <main className="min-h-screen bg-slate-100 p-4 text-slate-950 sm:p-8"><div className="mx-auto max-w-[1500px] space-y-6"><header className="rounded-3xl bg-[#071426] p-7 text-white shadow-xl"><p className="text-xs font-black uppercase tracking-[.2em] text-rose-300">Recovery Manager Portal · Account recovery register</p><h1 className="mt-2 text-3xl font-black">{labels[filter]}</h1><p className="mt-3 text-slate-300">Recovery attention, pre-NPL handoff and exposure visibility. Displayed 15 accounts per page.</p><Link href="/recovery-manager-portal#portfolio" className="mt-5 inline-flex rounded-xl border border-rose-400/50 px-4 py-2 text-sm font-black text-rose-300">Back to Recovery Dashboard</Link></header>
<section className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-wrap gap-2">{(Object.keys(labels) as Filter[]).map((key)=><button key={key} type="button" onClick={()=>choose(key)} className={`rounded-full px-4 py-2 text-sm font-black ${filter===key?"bg-slate-950 text-white":"border bg-white text-slate-700"}`}>{labels[key].replace(/ ·.*| Context| Register/,"")} ({records.filter((record)=>matches(record,key)).length})</button>)}</div><div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase text-slate-500">Matching accounts</p><p className="mt-1 text-4xl font-black">{category.length}</p></div><div className="w-full max-w-xl"><RegisterSearch value={query} onChange={(value)=>{setQuery(value);setPage(1)}} placeholder="Search borrower, account, branch, product, employer or officer" resultCount={filtered.length}/></div></div>
<div className="mt-6 overflow-x-auto"><table className="w-full min-w-[1150px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500">{["Borrower","Loan account","Branch","Product","Outstanding","Arrears","DPD","Risk","Repayment status","Recovery overlays","Responsible officer"].map((head)=><th key={head} className="px-3 py-3">{head}</th>)}</tr></thead><tbody>{visible.map((record)=><tr key={record.loan_account} className="border-b"><td className="px-3 py-3 font-bold">{record.member_name}</td><td className="px-3 py-3">{record.loan_account}</td><td className="px-3 py-3">{record.branch||"—"}</td><td className="px-3 py-3">{record.loan_product||"—"}</td><td className="px-3 py-3">{money(record.outstanding_balance)}</td><td className="px-3 py-3">{money(Number(record.arrears_amount||0))}</td><td className="px-3 py-3 font-bold">{record.days_in_arrears||0}</td><td className="px-3 py-3 font-black">{record.risk_status}</td><td className="px-3 py-3">{record.repayment_status||"Not specified"}</td><td className="max-w-xs px-3 py-3 text-xs">{[highExposure.has(record.loan_account)?"High Exposure":"",isRestructured(record)?"Restructured":"",...(record.risk_flags||[])].filter(Boolean).filter((value,index,all)=>all.indexOf(value)===index).join(" · ")||"None"}</td><td className="px-3 py-3">{record.responsible_officer||"Unassigned"}</td></tr>)}</tbody></table>{!visible.length&&<p className="py-10 text-center text-slate-500">No accounts match this category.</p>}</div><Pagination page={page} pageSize={PAGE_SIZE} totalItems={filtered.length} onPageChange={setPage}/></section></div></main>}
