"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import Pagination from "../../components/Pagination";
import RegisterSearch from "../../components/RegisterSearch";
import {isActionOverdue,isClosedActionStatus} from "@/lib/riskPolicy";
type Action={action_id?:string;loan_account:string;member_name:string;risk_status?:string;action_required?:string;assigned_to?:string;due_date?:string;status?:string;escalation_level?:string};
type Filter="open"|"overdue"|"escalated"|"unassigned";const PAGE_SIZE=15;
const titles:Record<Filter,{title:string;description:string}>={open:{title:"Open Management Actions",description:"All unresolved Execution Tracker actions."},overdue:{title:"Overdue Management Actions",description:"Open actions whose due date has passed."},escalated:{title:"Escalated Management Actions",description:"Open actions at Level 3 or Level 4 escalation."},unassigned:{title:"Unassigned Management Actions",description:"Open actions without an accountable owner."}};
export default function CeoActionsPage(){const[actions,setActions]=useState<Action[]>([]);const[filter,setFilter]=useState<Filter>("open");const[query,setQuery]=useState("");const[page,setPage]=useState(1);
useEffect(()=>{const requested=new URLSearchParams(window.location.search).get("filter") as Filter|null;if(requested&&requested in titles)setFilter(requested);try{const all=JSON.parse(localStorage.getItem("kiprod_action_items")||"[]") as Action[];setActions(all)}catch{setActions([])}},[]);
const category=useMemo(()=>actions.filter(a=>{if(isClosedActionStatus(a.status))return false;if(filter==="overdue")return isActionOverdue(a);if(filter==="escalated")return /Level [34]/.test(String(a.escalation_level||""));if(filter==="unassigned")return !String(a.assigned_to||"").trim();return true}),[actions,filter]);const filtered=useMemo(()=>{const term=query.trim().toLowerCase();if(!term)return category;return category.filter(a=>[a.action_id,a.loan_account,a.member_name,a.risk_status,a.action_required,a.assigned_to,a.status,a.escalation_level].some(v=>String(v||"").toLowerCase().includes(term)))},[category,query]);const visible=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
function choose(next:Filter){setFilter(next);setPage(1);setQuery("");window.history.replaceState(null,"",`/ceo-portal/actions?filter=${next}`)}
return <main className="min-h-screen bg-slate-100 p-4 text-slate-950 sm:p-8"><div className="mx-auto max-w-[1500px] space-y-6"><header className="rounded-3xl bg-slate-950 p-7 text-white shadow-xl"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-300">CEO Portal · Read-only accountability register</p><h1 className="mt-2 text-3xl font-black">{titles[filter].title}</h1><p className="mt-3 text-slate-300">{titles[filter].description} Displayed 15 rows per page.</p><Link href="/ceo-portal#accountability" className="mt-5 inline-flex rounded-xl border border-emerald-400/50 px-4 py-2 text-sm font-black text-emerald-300">Back to CEO Dashboard</Link></header>
<section className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-wrap gap-2">{(Object.keys(titles) as Filter[]).map(key=><button key={key} onClick={()=>choose(key)} className={`rounded-full px-4 py-2 text-sm font-black ${filter===key?"bg-slate-950 text-white":"border bg-white text-slate-700"}`}>{titles[key].title.replace(" Management Actions","")} ({actions.filter(a=>!isClosedActionStatus(a.status)&&(key==="open"||(key==="overdue"&&isActionOverdue(a))||(key==="escalated"&&/Level [34]/.test(String(a.escalation_level||"")))||(key==="unassigned"&&!String(a.assigned_to||"").trim()))).length})</button>)}</div><div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase text-slate-500">Matching actions</p><p className="mt-1 text-4xl font-black">{category.length}</p></div><div className="w-full max-w-xl"><RegisterSearch value={query} onChange={v=>{setQuery(v);setPage(1)}} placeholder="Search account, member, owner, action or escalation" resultCount={filtered.length}/></div></div>
<div className="mt-6 overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500">{["Action ID","Account","Member","Risk","Action required","Owner","Due date","Position","Escalation"].map(h=><th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody>{visible.map(a=><tr key={a.action_id||a.loan_account} className="border-b"><td className="px-3 py-3 font-bold">{a.action_id||"Legacy"}</td><td className="px-3 py-3">{a.loan_account}</td><td className="px-3 py-3">{a.member_name}</td><td className="px-3 py-3 font-bold">{a.risk_status||"Not set"}</td><td className="max-w-xs px-3 py-3">{a.action_required||"Follow-up required"}</td><td className="px-3 py-3">{a.assigned_to||"Unassigned"}</td><td className="px-3 py-3">{a.due_date||"Not set"}</td><td className={`px-3 py-3 font-black ${isActionOverdue(a)?"text-red-700":""}`}>{isActionOverdue(a)?"Overdue":a.status||"Open"}</td><td className="px-3 py-3">{a.escalation_level||"Not set"}</td></tr>)}</tbody></table>{!visible.length&&<p className="py-10 text-center text-slate-500">No actions match this category.</p>}</div><Pagination page={page} pageSize={PAGE_SIZE} totalItems={filtered.length} onPageChange={setPage}/></section></div></main>}
