"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabaseClient";
import {cachePortalClarifications,currentPortalRole,isManagementPending,MANAGEMENT_ROLES,PortalClarification,roleMatchesAssignment} from "@/lib/portalRouting";
const institutionId=()=>process.env.NEXT_PUBLIC_DEFAULT_INSTITUTION_ID||"";
export default function ManagementPortalPage(){
 const [role,setRole]=useState("MVP User");const [rows,setRows]=useState<PortalClarification[]>([]);const [message,setMessage]=useState("Loading assigned work...");
 async function load(){const id=institutionId();if(!id){setMessage("Institution ID is not configured.");return;}const {data,error}=await supabase.from("clarification_requests").select("*").eq("institution_id",id).order("created_at",{ascending:false});if(error){setMessage(error.message);return;}const next=(data||[]) as PortalClarification[];setRows(next);cachePortalClarifications(next);setMessage("");}
 useEffect(()=>{setRole(currentPortalRole());void load();},[]);function chooseRole(next:string){localStorage.setItem("kiprodCurrentRole",next);setRole(next);}const assigned=useMemo(()=>rows.filter(row=>roleMatchesAssignment(role,row.assigned_to)),[role,rows]);const pending=assigned.filter(row=>isManagementPending(row.status));
 return <main className="min-h-screen bg-slate-100 p-4 text-slate-950 sm:p-8"><div className="mx-auto max-w-7xl space-y-6">
 <header className="rounded-3xl bg-slate-950 p-7 text-white shadow-xl"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-400">Shared role-based workspace</p><h1 className="mt-3 text-4xl font-black">Management Portal</h1><p className="mt-3 text-slate-300">One shared portal, filtered to the risks, actions and Board clarifications assigned to the current management role.</p></header>
 <section className="rounded-2xl bg-white p-5 shadow-sm"><label className="text-sm font-bold">Current MVP role<select value={role} onChange={e=>chooseRole(e.target.value)} className="mt-2 block w-full max-w-md rounded-xl border p-3">{MANAGEMENT_ROLES.map(item=><option key={item}>{item}</option>)}</select></label><p className="mt-3 text-xs text-slate-500">This uses the existing role simulation. Production authentication and permissions remain a later security phase.</p></section>
 <section className="grid gap-4 sm:grid-cols-3">{[["New Board tasks",pending.length],["All assigned clarifications",assigned.length],["Responses submitted",assigned.filter(r=>r.status==="Management Responded"||r.status==="Under Board Review").length]].map(([label,value])=><div key={String(label)} className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm font-bold text-slate-600">{label}</p><p className="mt-2 text-4xl font-black">{value}</p></div>)}</section>
 <section className="grid gap-4 md:grid-cols-3"><Link href="/action-tracker" className="rounded-2xl bg-white p-5 font-black shadow-sm">My Execution Actions</Link><Link href="/watchlist" className="rounded-2xl bg-white p-5 font-black shadow-sm">Relevant Watchlist</Link><Link href="/clarification-requests" className="rounded-2xl bg-white p-5 font-black shadow-sm">Respond to Board</Link></section>
 <section className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-black">Board clarification tasks</h2><p className="text-sm text-slate-600">Only matters routed to {role} are shown.</p></div><button onClick={()=>void load()} className="rounded-xl border px-4 py-2 font-bold">Refresh</button></div>{message&&<p className="mt-4 text-sm text-slate-600">{message}</p>}<div className="mt-5 space-y-3">{pending.length?pending.map(row=><Link key={row.id} href="/clarification-requests" className="block rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{row.request_title}</strong><span className="rounded-full bg-amber-500 px-3 py-1 text-xs font-bold">{row.status}</span></div><p className="mt-2 text-sm">{row.loan_account||"No account"} · requested by {row.requested_by_role||"Board"}</p></Link>):<p className="rounded-2xl border border-dashed p-5 text-slate-600">No pending Board clarification is assigned to this role.</p>}</div></section>
 </div></main>;
}
