"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {defaultInstitutionProfile,loadMasterInstitutionProfile,type InstitutionProfile} from "@/lib/institutionMaster";
import {cachePortalClarifications,isManagementPending,type PortalClarification} from "@/lib/portalRouting";
import {getHighExposureLoanAccounts,isActionOverdue,isClosedActionStatus,isPar30,isRestructured,isWatchlistStatus,PAR30_SHORTHAND} from "@/lib/riskPolicy";
import {supabase} from "@/lib/supabaseClient";

type Loan={loan_account:string;member_name:string;branch?:string;loan_product?:string;employer?:string;loan_amount?:number;outstanding_balance:number;arrears_amount?:number;days_in_arrears?:number;responsible_officer?:string;restructured?:string;risk_flags?:string[];risk_status:"Green"|"Amber"|"Red"|"NPL"};
type Action={action_id?:string;loan_account:string;member_name:string;risk_status?:string;assigned_to?:string;due_date?:string;status?:string;escalation_level?:string};
type Audit={id:string;created_at:string;action_type:string;record_ref:string;role:string;note:string};
const iid=()=>process.env.NEXT_PUBLIC_DEFAULT_INSTITUTION_ID||"";const read=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||"") as T}catch{return fallback}};const sum=(values:number[])=>values.reduce((a,b)=>a+Number(b||0),0);const pct=(a:number,b:number)=>b?`${((a/b)*100).toFixed(1)}%`:"0.0%";const forCredit=(value:string|null|undefined)=>String(value||"").toLowerCase().includes("credit");

export default function CreditManagerPortalPage(){
const[profile,setProfile]=useState<InstitutionProfile>(defaultInstitutionProfile);const[records,setRecords]=useState<Loan[]>([]);const[actions,setActions]=useState<Action[]>([]);const[requests,setRequests]=useState<PortalClarification[]>([]);const[audits,setAudits]=useState<Audit[]>([]);const[selectedId,setSelectedId]=useState("");const[response,setResponse]=useState("");const[message,setMessage]=useState("");const[saving,setSaving]=useState(false);
async function load(){setRecords(read("kiprod_loan_records",[]));setActions(read("kiprod_action_items",[]));const id=iid();if(!id){setMessage("Institution ID is not configured for Board-request routing.");return}const[clarifications,audit]=await Promise.all([supabase.from("clarification_requests").select("*").eq("institution_id",id).order("created_at",{ascending:false}),supabase.from("audit_logs").select("id,created_at,action_type,record_ref,role,note").eq("institution_id",id).in("module",["Clarification Requests","Execution Tracker","Early Warning","Watchlist"]).order("created_at",{ascending:false}).limit(12)]);if(clarifications.error){setMessage(clarifications.error.message);return}const all=(clarifications.data||[]) as PortalClarification[];cachePortalClarifications(all);setRequests(all);setAudits((audit.data||[]) as Audit[]);const first=all.find((item)=>forCredit(item.assigned_to)&&isManagementPending(item.status));setSelectedId((current)=>current||first?.id||"");if(first)setResponse(first.management_response||"");setMessage("")}
useEffect(()=>{localStorage.setItem("kiprodCurrentRole","Credit Manager");loadMasterInstitutionProfile().then((result)=>setProfile(result.profile));void load()},[]);
const assignedRequests=useMemo(()=>requests.filter((item)=>forCredit(item.assigned_to)),[requests]);const pendingRequests=assignedRequests.filter((item)=>isManagementPending(item.status));const selected=assignedRequests.find((item)=>item.id===selectedId)||null;
const analysis=useMemo(()=>{const outstanding=sum(records.map((record)=>record.outstanding_balance));const arrears=sum(records.map((record)=>Number(record.arrears_amount||0)));const par30=records.filter((record)=>isPar30(record.days_in_arrears));const watchlist=records.filter((record)=>isWatchlistStatus(record.risk_status));const amber=records.filter((record)=>record.risk_status==="Amber");const red=records.filter((record)=>record.risk_status==="Red");const npl=records.filter((record)=>record.risk_status==="NPL");const highIds=getHighExposureLoanAccounts(records);const highExposure=records.filter((record)=>highIds.has(record.loan_account));const restructured=records.filter((record)=>isRestructured(record));const open=actions.filter((action)=>!isClosedActionStatus(action.status));const overdue=open.filter((action)=>isActionOverdue(action));const level2=open.filter((action)=>String(action.escalation_level||"").includes("Level 2"));const assigned=open.filter((action)=>forCredit(action.assigned_to));const priority=[...watchlist].sort((a,b)=>Number(b.outstanding_balance||0)-Number(a.outstanding_balance||0)).slice(0,10);return{outstanding,arrears,par30,watchlist,amber,red,npl,highExposure,restructured,open,overdue,level2,assigned,priority}},[records,actions]);
const concentrations=useMemo(()=>{const aggregate=(field:"branch"|"loan_product")=>{const map=new Map<string,{count:number,exposure:number}>();analysis.watchlist.forEach((record)=>{const key=String(record[field]||"Not specified");const current=map.get(key)||{count:0,exposure:0};current.count++;current.exposure+=Number(record.outstanding_balance||0);map.set(key,current)});return[...map.entries()].map(([name,value])=>({name,...value})).sort((a,b)=>b.exposure-a.exposure).slice(0,5)};return{branches:aggregate("branch"),products:aggregate("loan_product")}},[analysis.watchlist]);
const money=(value:number)=>`${profile.reportingCurrency||"KES"} ${Number(value||0).toLocaleString("en-KE",{maximumFractionDigits:0})}`;
const metric=(label:string,value:string|number,note:string,href?:string,tone="text-slate-950")=>{const content=<><p className="text-xs font-black uppercase text-slate-500">{label}</p><p className={`mt-2 text-3xl font-black ${tone}`}>{value}</p><p className="mt-2 text-xs text-slate-600">{note}</p>{href&&<span className="mt-3 inline-block text-[11px] font-black uppercase tracking-wide text-amber-700">Open full register</span>}</>;return href?<Link href={href} className="rounded-2xl border bg-white p-5 shadow-sm transition hover:border-amber-500 hover:shadow-md">{content}</Link>:<article className="rounded-2xl border bg-white p-5 shadow-sm">{content}</article>};
async function submit(){if(!selected||!response.trim()){setMessage("Select a Board request and add the Credit Manager response.");return}setSaving(true);const{error}=await supabase.from("clarification_requests").update({management_response:response.trim(),responded_at:new Date().toISOString(),status:"Management Responded"}).eq("id",selected.id);setSaving(false);if(error){setMessage(error.message);return}await supabase.from("audit_logs").insert({institution_id:iid(),module:"Clarification Requests",action_type:"MANAGEMENT_RESPONSE_SUBMITTED",record_ref:`${selected.loan_account||"No account"} - ${selected.request_title}`,old_value:selected.management_response||"No response",new_value:response.trim(),role:"Credit Manager",user_name:"Credit Manager",note:"Credit Manager response submitted to the Board Portal."});setResponse("");setSelectedId("");setMessage("Credit Manager response submitted. The Board has been notified.");await load()}
return <main className="min-h-screen bg-[#eef2f6] p-4 text-slate-950 sm:p-8"><div id="dashboard" className="mx-auto max-w-[1500px] space-y-7">
<header className="rounded-[2rem] bg-[#071426] p-8 text-white shadow-2xl"><p className="text-xs font-black uppercase tracking-[.22em] text-amber-300">Credit quality and intervention control</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Command Centre Credit Manager Dashboard</h1><p className="mt-4 max-w-3xl text-slate-300">Credit portfolio quality, early-warning cases, borrower intervention, action accountability and Board requests.</p></header>
<section className="rounded-3xl border border-amber-200 bg-amber-50 p-5"><p className="text-xs font-black uppercase text-amber-900">Credit Manager attention queue</p><p className="mt-1 font-semibold">{pendingRequests.length} Board tasks · {analysis.overdue.length} overdue actions · {analysis.level2.length} Level 2 reviews · {analysis.red.length} Red accounts</p></section>
<section id="portfolio" className="scroll-mt-24 space-y-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-amber-700">Credit portfolio command</p><h2 className="mt-1 text-2xl font-black">Credit quality position</h2></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metric("Outstanding portfolio",money(analysis.outstanding),`${records.length} accounts`)}{metric(`PAR30 · ${PAR30_SHORTHAND}`,pct(sum(analysis.par30.map((record)=>record.outstanding_balance)),analysis.outstanding),`${analysis.par30.length} accounts · ${money(sum(analysis.par30.map((record)=>record.outstanding_balance)))}`,"/credit-manager-portal/accounts?filter=par30","text-amber-800")}{metric("Total arrears",money(analysis.arrears),`${pct(analysis.arrears,analysis.outstanding)} of outstanding`)}{metric("Watchlist",analysis.watchlist.length,`${money(sum(analysis.watchlist.map((record)=>record.outstanding_balance)))} exposure`,"/credit-manager-portal/accounts?filter=watchlist")}</div></section>
<section className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><div className="rounded-3xl bg-[#071426] p-6 text-white shadow-xl"><p className="text-xs font-black uppercase tracking-[.18em] text-amber-300">Credit intervention bands</p><h2 className="mt-2 text-2xl font-black">Early-warning and handoff</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><Link href="/credit-manager-portal/accounts?filter=amber" className="rounded-2xl border border-amber-300/40 bg-amber-300/10 p-5"><strong className="text-3xl">{analysis.amber.length}</strong><span className="mt-2 block text-sm text-amber-100">Amber · monitor and correct</span></Link><Link href="/credit-manager-portal/accounts?filter=red" className="rounded-2xl border border-red-300/40 bg-red-400/10 p-5"><strong className="text-3xl">{analysis.red.length}</strong><span className="mt-2 block text-sm text-red-100">Red · manager intervention</span></Link><Link href="/credit-manager-portal/accounts?filter=npl" className="rounded-2xl border border-fuchsia-300/40 bg-fuchsia-400/10 p-5"><strong className="text-3xl">{analysis.npl.length}</strong><span className="mt-2 block text-sm text-fuchsia-100">NPL · recovery handoff</span></Link></div></div><div className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[.18em] text-amber-700">Credit overlays</p><h2 className="mt-2 text-2xl font-black">Enhanced review</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><Link href="/credit-manager-portal/accounts?filter=early-warning" className="rounded-2xl border p-4"><strong className="text-2xl">{analysis.amber.length+analysis.red.length}</strong><span className="mt-1 block text-sm text-slate-600">Early-warning cases</span></Link><Link href="/credit-manager-portal/accounts?filter=high-exposure" className="rounded-2xl border p-4"><strong className="text-2xl">{analysis.highExposure.length}</strong><span className="mt-1 block text-sm text-slate-600">High-exposure Watchlist</span></Link><Link href="/credit-manager-portal/accounts?filter=restructured" className="rounded-2xl border p-4"><strong className="text-2xl">{analysis.restructured.length}</strong><span className="mt-1 block text-sm text-slate-600">Restructured credit</span></Link><div className="rounded-2xl border p-4"><strong className="text-2xl">{analysis.npl.length}</strong><span className="mt-1 block text-sm text-slate-600">Recovery handoffs</span></div></div></div></section>
<section className="grid gap-6 lg:grid-cols-2"><div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Watchlist by product</h2><div className="mt-4 space-y-3">{concentrations.products.map((item)=><div key={item.name} className="flex justify-between gap-4 rounded-xl bg-slate-100 p-3"><span><strong>{item.name}</strong><small className="block text-slate-500">{item.count} accounts</small></span><strong>{money(item.exposure)}</strong></div>)}</div></div><div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Watchlist by branch</h2><div className="mt-4 space-y-3">{concentrations.branches.map((item)=><div key={item.name} className="flex justify-between gap-4 rounded-xl bg-slate-100 p-3"><span><strong>{item.name}</strong><small className="block text-slate-500">{item.count} accounts</small></span><strong>{money(item.exposure)}</strong></div>)}</div></div></section>
<section id="actions" className="scroll-mt-24 space-y-4"><h2 className="text-2xl font-black">Credit action accountability</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metric("Open actions",analysis.open.length,"All unresolved portfolio actions","/credit-manager-portal/actions?filter=open")}{metric("Overdue",analysis.overdue.length,"Due date passed and not closed","/credit-manager-portal/actions?filter=overdue","text-red-700")}{metric("Level 2 reviews",analysis.level2.length,"Credit Manager review level","/credit-manager-portal/actions?filter=credit-review")}{metric("Assigned to Credit",analysis.assigned.length,"Direct Credit Manager ownership","/credit-manager-portal/actions?filter=assigned")}</div></section>
<section className="overflow-x-auto rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase text-amber-700">Exposure-led intervention</p><h2 className="mt-1 text-2xl font-black">Priority credit accounts</h2></div><Link href="/credit-manager-portal/accounts?filter=early-warning" className="rounded-xl border px-4 py-2 text-sm font-black">Open Early Warning</Link></div><table className="mt-5 w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500">{["Account","Borrower","Risk","DPD","Outstanding","Product","Branch","Responsible officer"].map((head)=><th key={head} className="px-3 py-3">{head}</th>)}</tr></thead><tbody>{analysis.priority.map((record)=><tr key={record.loan_account} className="border-b"><td className="px-3 py-3 font-bold">{record.loan_account}</td><td className="px-3 py-3">{record.member_name}</td><td className="px-3 py-3 font-black">{record.risk_status}</td><td className="px-3 py-3">{record.days_in_arrears||0}</td><td className="px-3 py-3">{money(record.outstanding_balance)}</td><td className="px-3 py-3">{record.loan_product||"—"}</td><td className="px-3 py-3">{record.branch||"—"}</td><td className="px-3 py-3">{record.responsible_officer||"Unassigned"}</td></tr>)}</tbody></table></section>
<section id="board-requests" className="grid scroll-mt-24 gap-6 xl:grid-cols-2"><div className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex justify-between gap-4"><div><h2 className="text-2xl font-black">Board clarification inbox</h2><p className="text-sm text-slate-600">Only matters routed to the Credit Manager.</p></div><button type="button" onClick={()=>void load()} className="rounded-xl border px-4 py-2 font-bold">Refresh</button></div><div className="mt-5 space-y-3">{pendingRequests.map((request)=><button key={request.id} type="button" onClick={()=>{setSelectedId(request.id);setResponse(request.management_response||"")}} className={`w-full rounded-2xl border p-4 text-left ${selectedId===request.id?"border-amber-500 bg-amber-50":""}`}><strong>{request.request_title}</strong><p className="mt-2 text-xs">{request.loan_account||"Portfolio-level"} · {request.status}</p></button>)}{!pendingRequests.length&&<p className="rounded-2xl border border-dashed p-5 text-slate-600">No Board clarification is awaiting a Credit Manager response.</p>}</div></div><div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">Respond to the Board</h2>{selected?<div className="mt-5 space-y-4"><div className="rounded-2xl bg-slate-100 p-4"><p className="text-xs font-black uppercase text-slate-500">Board question</p><p className="mt-2 whitespace-pre-wrap text-sm">{selected.question}</p></div><textarea value={response} onChange={(event)=>setResponse(event.target.value)} className="min-h-40 w-full rounded-xl border p-3" placeholder="Credit assessment, borrower intervention, owner and committed timeline"/><button type="button" disabled={saving} onClick={()=>void submit()} className="rounded-xl bg-amber-600 px-5 py-3 font-black text-slate-950 disabled:opacity-60">{saving?"Submitting…":"Submit response to Board"}</button></div>:<p className="mt-5 text-slate-600">Select a Board request to review and respond.</p>}</div></section>
<section id="audit" className="scroll-mt-24 rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">Credit-relevant audit trail</h2><div className="mt-4 divide-y">{audits.map((audit)=><div key={audit.id} className="grid gap-1 py-3 sm:grid-cols-[180px_1fr_150px]"><span className="text-xs text-slate-500">{new Date(audit.created_at).toLocaleString("en-KE")}</span><div><strong>{audit.action_type.replaceAll("_"," ")}</strong><p className="text-xs text-slate-600">{audit.record_ref} · {audit.note}</p></div><span className="text-xs font-bold">{audit.role}</span></div>)}{!audits.length&&<p className="py-5 text-slate-500">No relevant audit events are available.</p>}</div></section>{message&&<p className="rounded-2xl bg-slate-950 p-4 text-sm font-bold text-white">{message}</p>}
</div></main>}
