"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { defaultInstitutionProfile, loadMasterInstitutionProfile, type InstitutionProfile } from "@/lib/institutionMaster";

const items = [["Dashboard","/board-portal#dashboard"],["Watchlist","/board-portal/watchlist"],["Open Actions","/board-portal/actions"],["Board Reports","/board-portal#reports"],["Clarifications","/board-portal#clarifications"],["Board Decisions","/board-portal#decisions"],["Audit Trail","/board-portal#audit"]];

export default function BoardPortalNav(){
 const [open,setOpen]=useState(false); const [profile,setProfile]=useState<InstitutionProfile>(defaultInstitutionProfile); const [role,setRole]=useState("Board User");
 useEffect(()=>{loadMasterInstitutionProfile().then(result=>setProfile(result.profile));setRole(localStorage.getItem("kiprodCurrentRole")||"Board User");},[]);
 return <header className="sticky top-0 z-50 border-b border-amber-400/30 bg-[#071426] text-white shadow-xl"><div className="mx-auto flex max-w-[1600px] items-center justify-between gap-4 px-4 py-3 sm:px-7"><Link href="/board-portal" className="flex min-w-0 items-center gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-amber-400/40 bg-amber-400/10 font-black text-amber-400">K</span><span className="min-w-0"><span className="block text-[10px] font-black uppercase tracking-[.2em] text-amber-400">Command Centre · Board Portal</span><strong className="block truncate text-sm sm:text-base">{profile.institutionName||"Institution"}</strong></span></Link><nav className="hidden items-center gap-1 xl:flex" aria-label="Board Portal menu">{items.map(([label,href])=><Link key={label} href={href} className="rounded-lg px-3 py-2 text-xs font-bold text-slate-200 hover:bg-white/10 hover:text-white">{label}</Link>)}</nav><div className="hidden items-center gap-3 sm:flex"><span className="rounded-full border border-white/15 bg-white/5 px-3 py-2 text-xs font-bold">{role}</span><Link href="/" className="rounded-lg border border-amber-400/40 px-3 py-2 text-xs font-black text-amber-300">Exit portal</Link></div><button type="button" onClick={()=>setOpen(value=>!value)} className="rounded-xl border border-amber-400/40 px-4 py-2 text-sm font-black xl:hidden" aria-expanded={open}>Board menu</button></div>{open&&<nav className="grid gap-1 border-t border-white/10 p-4 xl:hidden" aria-label="Board Portal mobile menu">{items.map(([label,href])=><Link key={label} href={href} onClick={()=>setOpen(false)} className="rounded-xl bg-white/5 px-4 py-3 text-sm font-bold">{label}</Link>)}<Link href="/" className="rounded-xl bg-amber-500 px-4 py-3 text-sm font-black text-slate-950">Exit portal</Link></nav>}</header>;
}
